### ISSUE TITLE
filtr.search not working : AttributeError: 'list' object has no attribute 'apply'

### ISSUE THREAD

**Issue by MohamedLEGH** [exleym/Flask-Filter#23]
Versions of libraries:
```python3
Flask==1.1.1
Flask-SQLAlchemy==2.3.2
Flask-Marshmallow==0.10.0
marshmallow==2.20.2
Marshmallow-Sqlalchemy==0.16.1
Flask-Filter==0.1.0.dev4
```
##
I try to run the filter extension with my Flask application like in the **Example 3** but it didn't work.
When calling the **search** route, the application stop at the line **filtr.search(...)**

```python3
    def search(self, DbModel: Model, filters: list,
               ModelSchema: Union[Schema, None] = None,
               limit: int = None, order_by=None):
        filters = self.schema.load(filters, many=True)
        schema = ModelSchema or self._lookup_schema(DbModel)
        query = DbModel.query
        for f in filters:
>           query = f.apply(query, DbModel, schema)
E           AttributeError: 'list' object has no attribute 'apply'

```
I try to run the filter extension manually like in the **Example 1** but I received the same error.
##
The problem can be resolved by changing  `for f in filters:` by `for f in filters.data:`
Unfortunately that means I cannot use **filtr.search**.

Any idea where the problem is from ? Older version of a library ?

**Comment by exleym** [comment]
Can you give an example of the request body that is causing the error? It sounds like the body of your search query is deserializing to a list of lists rather than a list of filter objects. Are you structuring your filter search like so?
```json
{
  "filters": [
    { 
      "value": 100,
      "op": "<",
      "field": "weight"
    }
  ]
}
``` 

If you are, the expected behavior is that the `FlaskFilter` instance would receive the list of "filters" passed to it when you called `filtr.search(Dog, request.json.get("filters"),  DogSchema)` and deserialize them to a list of objects that all subclass the base class `flask_filter.filters.filters.Filter`

**Comment by MohamedLEGH** [comment]
Yes I'm structuring my filter search like this:
```python 
data = { "filters": [ {"field": "username", "op": "like", "value": "test"} ] }
response = client.post("/users/search",json=data)
```

**Comment by exleym** [comment]
After looking into this a little more, this is because you're using marshmallow 2.x, which deserializes into `<class 'marshmallow.schema.UnmarshalResult'>` rather than into the objects itself. 

The relevant breaking API changes in Marshmallow 3.0 are shown here:

```python
from marshmallow import Schema, fields

class TestSchema(Schema):
    id = fields.Integer()
    name = fields.String()

schema = TestSchema()
data = [{"id": 1, "name" : "Test Name"}]

# Marshmallow 2.x
foo = schema.load(data, many=True)  # <class 'marshmallow.schema.UnmarshalResult'>
print(foo.data)  # [{"id": 1, "name" : "Test Name"}]

# Marshmallow 3.x
foo = schema.load(data, many=True)  # [{"id": 1, "name" : "Test Name"}]
print(foo.data)  # should raise an AttributeError
```

All of this is to say that the documentation should be more clear that the current implementation only supports marshmallow  3.0+.

Is there a reason you are pegged to marshmallow 2.x for your project? If so, I can add conditional behavior to support both, but at this point, new projects should be using 3.x, so I was hoping to avoid the overhead of a version check in the deserialization.

**Comment by MohamedLEGH** [comment]
Ok thanks for the answer.
We will change the requirement for marshmallow 3.0+ on our project when we will have time, don't worry, in the meantime we have the workaround with filters.data.
You don't need to add conditional behavior, I'm closing the issue.

**Comment by exleym** [comment]
There was an easy, low-overhead way to do this, so i did it anyway. Libraries should support as wide a range of dependencies as possible, and leave the opinion to the applications. Release 0.1.0.dev5 should cover you.

**Comment by MohamedLEGH** [comment]
Thanks a lot !
